# Generated by Django 5.0.4 on 2024-04-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='openAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('scheduled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='drData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('rg', models.ImageField(upload_to='rgs')),
                ('medicalID', models.ImageField(upload_to='mid')),
                ('photo', models.ImageField(upload_to='photos')),
                ('description', models.TextField(blank=True, null=True)),
                ('appointmentValue', models.FloatField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.specialties')),
            ],
        ),
    ]
