# Generated by Django 5.0.4 on 2024-04-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_agenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.openagenda')),
            ],
        ),
    ]
