# Generated by Django 5.0.6 on 2024-05-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('F', 'Finished'), ('C', 'Cancelled'), ('I', 'Initilized')], default='S', max_length=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('open_agenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.openagenda')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='documents')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.appointment')),
            ],
        ),
    ]
