# Generated by Django 5.2 on 2025-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('F', 'Finished'), ('C', 'Cancelled'), ('I', 'Initialized')], default='S', max_length=1),
        ),
    ]
